trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'DevOpsVM'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/tmp/website'

- task: SSH@0
  inputs:
    sshEndpoint: 'DevOpsVM'
    runOptions: 'commands'
    commands: |
      sudo cp -r /tmp/website/* /var/www/html/
      sudo systemctl restart nginx